image: openjdk:15-jdk-slim

pipelines:
  pull-requests:
    '**':
      - step:
          name: snyk scan
          script:
            - pipe: snyk/snyk-scan:0.4.6
              variables:
                SNYK_TOKEN: $SNYK_TOKEN
                CODE_INSIGHTS_RESULTS: "true"
                DONT_BREAK_BUILD: "true"
                LANGUAGE: "gradle"
